// Copyright (c) 2026 Justine Louise.
// Created by Justine Louise.
//
// This software is provided for personal and educational use only.
// Commercial use, resale, or distribution for profit is strictly prohibited
// without prior written permission from the author.
//
// Please respect the developer's work.
// Do not remove or modify this copyright notice or claim this project as your own.
//
// © 2026 Justine Louise. All Rights Reserved.
// ® Powered By Zapo-js
// plugins/owner/createthumb.js

import { config } from '../../settings.js'

export default {
  command: 'ct',
  alias: ['createthumbnail'],
  category: 'owner',
  description: 'Membuat thumbnail preview kustom dari URL atau reply gambar.\n\n' +
    '*Format Penggunaan:*\n' +
    '> `Menggunakan URL gambar`\n> .ct <url>\n\n' +
    '> `Menggunakan URL gambar dan favicon`\n> .ct <url>, <url favicon>\n\n' +
    '> `Menggunakan gambar yang di-reply`\n> .ct',
  help: '(reply/url)',
  typing: true,
  wait: true,

  async execute(m, { sock, args }) {

    const raw = args.join(' ')
    const [rawMain, rawFavicon] = raw.split(',').map(s => s?.trim())

    const hasQuotedImage = m.quoted?.type === 'imageMessage'
    const useQuotedAsMain = !rawMain && hasQuotedImage

    if (!rawMain && !useQuotedAsMain) {
      return m.reply('Kirim URL gambar atau reply gambar!\n\nContoh:\n• ct <url>\n• ct <url>, <url favicon>\n• reply gambar lalu ketik: ct\n• reply gambar lalu ketik: ct ,<url favicon>')
    }

    const mainImage = useQuotedAsMain
      ? await m.quoted.download()
      : rawMain

    const meta = await sock.uploadThumbnail(mainImage)

    if (rawFavicon) {
      const faviconMeta = await sock.uploadThumbnail(rawFavicon, { favicon: true })
      meta.faviconMmsMetadata = {
        thumbnailDirectPath: faviconMeta.thumbnailDirectPath,
        thumbnailSha256: faviconMeta.thumbnailSha256,
        thumbnailEncSha256: faviconMeta.thumbnailEncSha256,
        mediaKey: faviconMeta.mediaKey,
        mediaKeyTimestamp: faviconMeta.mediaKeyTimestamp,
        thumbnailWidth: faviconMeta.thumbnailWidth,
        thumbnailHeight: faviconMeta.thumbnailHeight
      }
    }

    const targetUrl = 'https://chat.whatsapp.com'

    await m.reply({
      extendedTextMessage: {
        title: 'ini Title',
        description: 'ini deskripsi',
        text: `${targetUrl}\n\nGenerated by ${config.botName}. \n> dari zapo library.`,
        matchedText: targetUrl,
        previewType: 0,
        inviteLinkGroupTypeV2: 0,
        ...meta
      }
    })
  }
}
